export const data = [
  {
    id: 1,
    label: "我的关注",
    order: 0,
    icon: "fav",
    children: [],
  },
  {
    id: 2,
    label: "前端框架",
    order: 1,
    icon: "html5",
    children: [
      {
        title: "vuejs",
        desc: "一款用于构建 Web 界面，易学易用，性能出色且功能丰富的框架。",
        logoUrl: "https://img1.imgtp.com/2022/07/14/aOJXDAoy.svg",
        siteUrl: "https://cn.vuejs.org/",
      },
      {
        title: "react",
        desc: "React 官方中文文档 – 用于构建用户界面的 JavaScript 库",
        logoUrl: "https://img1.imgtp.com/2022/07/26/HZVaHD5Y.svg",
        siteUrl: "https://react.docschina.org/",
      },
      {
        title: "Angular",
        desc: "Angular is a platform for building mobile and desktop web applications.",
        logoUrl: "https://img1.imgtp.com/2022/07/26/MF7hYxiR.svg",
        siteUrl: "https://angular.io/",
      },
      {
        title: "Svelte",
        desc: "Cybernetically enhanced web apps",
        logoUrl: "https://img1.imgtp.com/2022/07/26/QTR589t0.png",
        siteUrl: "https://svelte.dev/",
      },
      {
        title: "preact",
        desc: "Fast 3kB alternative to React with the same modern API",
        logoUrl: "https://img1.imgtp.com/2022/07/26/jXCOnIj3.png",
        siteUrl: "https://preactjs.com/",
      },
      {
        title: "solidjs",
        desc: "Solid is a purely reactive library. It was designed from the ground up with a reactive core. It's influenced by reactive principles developed by previous libraries.",
        logoUrl: "https://img1.imgtp.com/2022/07/27/O1u7FTex.svg",
        siteUrl: "https://www.solidjs.com/",
      },
      {
        title: "vue-router",
        desc: "Vue.js 的官方路由",
        logoUrl: "https://img1.imgtp.com/2022/07/14/aOJXDAoy.svg",
        siteUrl: "https://router.vuejs.org/zh/",
      },
      {
        title: "react-router",
        desc: "React 官网路由",
        logoUrl: "https://img1.imgtp.com/2022/08/01/abkNGIVK.png",
        siteUrl: "https://reactrouter.com/",
      },
      {
        title: "pinia",
        desc: "The Vue Store that you will enjoy using",
        logoUrl: "https://img1.imgtp.com/2022/08/01/Axgv0ocD.svg",
        siteUrl: "https://pinia.vuejs.org/",
      },
      {
        title: "vuex",
        desc: "Vue.js 的中心化状态管理方案",
        logoUrl: "https://img1.imgtp.com/2022/07/14/aOJXDAoy.svg",
        siteUrl: "https://vuex.vuejs.org/zh/",
      },
      {
        title: "redux",
        desc: "JavaScript应用程序的可预测状态容器。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/4nnulRzi.svg",
        siteUrl: "https://redux.js.org/",
      },
      {
        title: "Rematch",
        desc: "Rematch is Redux best practices without the boilerplate",
        logoUrl: "https://img1.imgtp.com/2022/08/01/nONVGJ7k.svg",
        siteUrl: "https://rematchjs.bootcss.com/",
      },
      {
        title: "recoil",
        desc: "A state management library for React.",
        logoUrl: "https://img1.imgtp.com/2022/08/01/3yM1LdXB.svg",
        siteUrl: "https://recoiljs.org/zh-hans/",
      },
      {
        title: "nextjs",
        desc: "Next.js 支持规模化的生产级 React 应用程序。大量世界领先的公司都在使用 Next.js 来构建静态和动态网站及 web 应用。",
        logoUrl: "https://img1.imgtp.com/2022/08/04/SI7P8qfs.svg",
        siteUrl: "https://www.nextjs.cn/",
      },
      {
        title: "nuxtjs",
        desc: "使用 Vue 3 构建您的下一个应用，体验混合渲染、强大的数据获取和新功能。 Nuxt 3 是一个开源框架，使 Web 开发变得简单而强大。",
        logoUrl: "https://img1.imgtp.com/2022/08/04/Ls8ZREv6.svg",
        siteUrl: "https://www.nuxtjs.org.cn/",
      },
    ],
  },
  {
    id: 3,
    label: "开发社区",
    order: 4,
    icon: "question-answer",
    children: [
      {
        title: "github",
        desc: "全世界最大的开源代码仓库",
        logoUrl: "https://img1.imgtp.com/2022/07/29/2VLOweww.svg",
        siteUrl: "https://github.com",
      },
      {
        title: "gitee",
        desc: "Gitee.com（码云） 是 OSCHINA.NET 推出的代码托管平台，支持 Git 和 SVN，提供免费的私有仓库托管。目前已有超过 800 万的开发者选择 Gitee。",
        logoUrl: "https://img1.imgtp.com/2022/07/30/nrxcv6p9.svg",
        siteUrl: "https://gitee.com/",
      },
      {
        title: "掘金",
        desc: "掘金是面向全球中文开发者的技术内容分享与交流平台。我们通过技术文章、沸点、课程、直播等产品和服务，打造一个激发开发者创作灵感，激励开发者沉淀分享，陪伴开发者成长的综合类技术社区。",
        logoUrl: "https://img1.imgtp.com/2022/07/30/6f3MO3zK.svg",
        siteUrl: "https://juejin.cn/",
      },
      {
        title: "segmentfault-思否",
        desc: "SegmentFault 思否是中国领先的开发者技术社区。我们以技术问答、技术专栏、技术课程、技术资讯为核心的产品形态，为开发者提供纯粹、高质的技术交流平台。",
        logoUrl: "https://img1.imgtp.com/2022/07/30/41I7vJOI.svg",
        siteUrl: "https://segmentfault.com/",
      },
      {
        title: "stack overflow",
        desc: "Stack Overflow is the largest, most trusted online community for developers to learn, share their programming knowledge, and build their careers.",
        logoUrl: "https://img1.imgtp.com/2022/07/27/DeWzCBFw.svg",
        siteUrl: "https://stackoverflow.com/",
      },
      {
        title: "CSDN",
        desc: "CSDN是全球知名中文IT技术交流平台,创建于1999年,包含原创博客、精品问答、职业培训、技术论坛、资源下载等产品服务,提供原创、优质、完整内容的专业IT技术开发社区.",
        logoUrl: "https://img1.imgtp.com/2022/08/06/jrfNnUYH.svg",
        siteUrl: "https://www.csdn.net/",
      },
      {
        title: "博客园",
        desc: "博客园是一个面向开发者的知识分享社区。",
        logoUrl: "https://img1.imgtp.com/2022/08/06/yBJEnBgt.svg",
        siteUrl: "https://www.cnblogs.com/",
      },
      {
        title: "开源中国",
        desc: "OSCHINA.NET 是目前领先的中文开源技术社区。我们传播开源的理念，推广开源项目，为 IT 开发者提供了一个发现、使用、并交流开源技术的平台",
        logoUrl: "https://img1.imgtp.com/2022/08/06/7HTpsKY9.svg",
        siteUrl: "https://www.oschina.net/",
      },
    ],
  },
  {
    id: 4,
    label: "实用工具",
    order: 5,
    icon: "tools",
    children: [
      {
        title: "Regex101",
        desc: "Regular expression tester with syntax highlighting, explanation, cheat sheet for PHP/PCRE, Python, GO, JavaScript, Java, C#/.NET.",
        logoUrl: "https://img1.imgtp.com/2022/08/16/gjaayhex.png",
        siteUrl: "https://regex101.com/",
      },
      {
        title: "正则大全",
        desc: "在线正则大全",
        logoUrl: "https://img1.imgtp.com/2022/07/29/2VLOweww.svg",
        siteUrl: "https://any86.github.io/any-rule/",
      },
      {
        title: "TinyPNG",
        desc: "让你的网站更快，节省带宽。TinyPNG将您的WebP、PNG和JPEG图像优化50-80%，同时保持完全透明！",
        logoUrl: "https://img1.imgtp.com/2022/07/29/J4tj0ax4.png",
        siteUrl: "https://tinypng.com/",
      },
      {
        title: "纯色占位图",
        desc: "Dynamic Dummy Image Generator",
        logoUrl: "https://img1.imgtp.com/2022/07/31/eAkKBqfF.png",
        siteUrl: "https://dummyimage.com/",
      },
      {
        title: "RegExr正则学习",
        desc: "带有语法高亮的、支持PHP / PCRE 和 JS 语言、 上下文解释、 备忘单、参考 和 正则表达式社区的正则表达式测试工具",
        logoUrl: "https://img1.imgtp.com/2022/08/01/4Q2kCKcl.png",
        siteUrl: "https://regexr-cn.com/",
      },
      {
        title: "JSON格式化",
        desc: "提供相关的Json解析、验证、格式化、压缩、编辑器以及Json与XML相互转换等服务",
        logoUrl: "https://img1.imgtp.com/2022/08/01/XVGZkYIS.png",
        siteUrl: "https://www.json.cn/",
      },
      {
        title: "JSON转Typescript",
        desc: "立即从JSON生成TypeScript接口。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/JiDs56b5.svg",
        siteUrl: "https://quicktype.io/typescript",
      },
      {
        title: "codeif命名神器",
        desc: "从Github、Bitbucket、Google Code、Codeplex、Sourceforge、Fedora Project、GitLab中搜索项目，以查找实际使用变量名。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/Kgar4Zu4.svg",
        siteUrl: "https://unbug.github.io/codelf/",
      },
      {
        title: "Convertio文件转换器",
        desc: "Convertio - 在线转换文件的简单工具。支持超过309种不同的文档、图像、电子表格、电子书、文档、演示文稿、音频和视频格式。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/8HGKh9EG.svg",
        siteUrl: "https://convertio.co/zh/",
      },
      {
        title: "png转ico",
        desc: "轻松将 PNG 图像转换为 ICO 格式！ 这个免费的转换器将使您能够快速将任何.png图像转换为.ico格式，而不会降低质量。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/PFxN3uig.png",
        siteUrl: "https://pngtoicon.com/cn",
      },
      {
        title: "免费图床",
        desc: "简单易操作，免费且不压缩图片画质的公共图床平台，支持对接PicGo。从本地相册选取图片上传到图床服务器快速获取图片外链。支持批量上传！",
        logoUrl: "https://img1.imgtp.com/2022/08/02/MK4QTBkv.svg",
        siteUrl: "https://www.imgtp.com/",
      },
      {
        title: "百度脑图",
        desc: "百度脑图，便捷的脑图编辑工具 - 控制创意，如此简单。",
        logoUrl: "https://img1.imgtp.com/2022/08/03/Wk9iNEOI.svg",
        siteUrl: "https://naotu.baidu.com/",
      },
      {
        title: "processOn",
        desc: "专业强大的作图工具，支持多人实时在线协作，可用于原型图、UML、BPMN、网络拓扑图等多种图形绘制",
        logoUrl: "https://img1.imgtp.com/2022/08/03/U4McVpaP.svg",
        siteUrl: "https://www.processon.com/",
      },
      {
        title: "linux命令搜索",
        desc: "Linux命令搜索引擎:最专业的Linux命令大全，内容包含Linux命令手册、详解、学习，值得收藏的Linux命令速查手册。",
        logoUrl: "https://img1.imgtp.com/2022/08/06/O7hTeTHN.svg",
        siteUrl: "https://wangchujiang.com/linux-command/",
      },
      {
        title: "Can I Use",
        desc: '"Can I use" provides up-to-date browser support tables for support of front-end web technologies on desktop and mobile web browsers.',
        logoUrl: "https://img1.imgtp.com/2022/08/06/jqABLNHt.svg",
        siteUrl: "https://caniuse.com/",
      },
      {
        title: "30 seconds of code",
        desc: "Browse 1157 short code snippets for all your development needs on 30 seconds of code.",
        logoUrl: "https://img1.imgtp.com/2022/08/06/dzqji9Ev.png",
        siteUrl: "https://www.30secondsofcode.org/",
      },
    ],
  },
  {
    id: 5,
    label: "图片资源",
    order: 7,
    icon: "image",
    children: [
      {
        title: "雪碧图生成器",
        desc: "Generate CSS image sprites from multiple images with our easy-to-use uploading tool. Get started for free.",
        logoUrl: "https://img1.imgtp.com/2022/07/29/Tmz3JBJ0.svg",
        siteUrl: "https://www.toptal.com/developers/css/sprite-generator",
      },
      {
        title: "Lorem Picsum",
        desc: "The Lorem Ipsum for photos.",
        logoUrl: "https://img1.imgtp.com/2022/07/31/2zi9AF9a.svg",
        siteUrl: "https://picsum.photos/",
      },
      {
        title: "pexels",
        desc: "免费素材图片和视频，可以在任何地方使用。✓ 高质量 ✓ 100% 免费✓ 无需注明归属",
        logoUrl: "https://img1.imgtp.com/2022/07/31/tYjHNTU7.svg",
        siteUrl: "https://www.pexels.com/zh-cn/",
      },
      {
        title: "unsplash",
        desc: "好看的免费图片和照片，你可以下载并用于任何项目。比任何免版税或库存照片都要好。",
        logoUrl: "https://img1.imgtp.com/2022/07/31/pUaYyQnB.svg",
        siteUrl: "https://unsplash.com/",
      },
    ],
  },
  {
    id: 6,
    label: "代码平台",
    order: 6,
    icon: "code",
    children: [
      {
        title: "codesandbox",
        desc: "CodeSandbox is an online code editor and prototyping tool that makes creating and sharing web apps faster",
        logoUrl: "https://img1.imgtp.com/2022/07/30/m0F6FUl5.svg",
        siteUrl: "https://codesandbox.io/",
      },
      {
        title: "codePen",
        desc: "An online code editor, learning environment, and community for front-end web development using HTML, CSS and JavaScript code snippets, projects, and web applications.",
        logoUrl: "https://img1.imgtp.com/2022/07/30/GqnXEFOS.svg",
        siteUrl: "https://codepen.io/",
      },
      {
        title: "stackblitz",
        desc: "Stay in the flow with instant dev experiences. No more hours stashing/pulling/installing locally — just click, and start coding.",
        logoUrl: "https://img1.imgtp.com/2022/07/30/mZOLX5RY.svg",
        siteUrl: "https://stackblitz.com/",
      },
      {
        title: "PLAYCODE",
        desc: "Super sleek javascript playground with instant live preview and console.",
        logoUrl: "https://img1.imgtp.com/2022/08/12/gxpRXsKO.svg",
        siteUrl: "https://playcode.io/",
      },
    ],
  },
  {
    id: 7,
    label: "设计资源",
    order: 12,
    icon: "palette",
    children: [
      {
        title: "Free Vector Illustra",
        desc: "免费下载设计素材-图标、照片、用户体验插图和视频音乐",
        logoUrl: "https://img1.imgtp.com/2022/07/31/N8vdmGYy.png",
        siteUrl: "https://icons8.com/illustrations",
      },
      {
        title: "传统中国色",
        desc: "提供各种中国的传统颜色的名称，CMYK值，RGB值，16进制表示。",
        logoUrl: "https://img1.imgtp.com/2022/07/31/VeXFSVef.png",
        siteUrl: "http://zhongguose.com/",
      },
      {
        title: "渐变色(WebGradients)",
        desc: "访问 WebGradients.com，了解 CSS3、Photoshop 和 Sketch 中的 180 种漂亮的线性渐变。 该系列由顶级设计师策划，完全免费。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/WGGds1WH.svg",
        siteUrl: "https://webgradients.com/",
      },
      {
        title: "渐变色(uigradients)",
        desc: "为设计师和开发人员精心挑选的漂亮颜色渐变系列",
        logoUrl: "https://img1.imgtp.com/2022/08/01/I1HznmN0.svg",
        siteUrl: "https://uigradients.com/",
      },
      {
        title: "豆皮儿UI",
        desc: "doupir豆皮儿网是一个专注于UI领域的垂直素材资源共享平台，旨在为UI设计师提供基础UI设计素材，并逐步打造成为一个垂直的素材交流平台。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/2I6D89WC.svg",
        siteUrl: "https://www.doupir.com/",
      },
      {
        title: "dribbble",
        desc: "在 Dribbble 上寻找顶级设计师和创意专业人士。 我们是设计师获得灵感、反馈、社区和工作的地方。 您发现并与全球设计师联系的最佳资源。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/MzCv9Ibs.svg",
        siteUrl: "https://dribbble.com/",
      },
      {
        title: "色盘",
        desc: " Hey Designers & Developers! We have a set of tools that include Material Color Palette, Flat UI Color Palette, Icons, Unicodes & more.",
        logoUrl: "https://img1.imgtp.com/2022/08/01/6JGpwXaA.svg",
        siteUrl: "https://materialui.co/",
      },
      {
        title: "色轮(adobe color)",
        desc: "使用色轮或影像建立调色盘，或浏览 Adobe Color 社群中的数千个颜色组合。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/ccTnecuj.svg",
        siteUrl: "https://color.adobe.com/zh/create/color-wheel",
      },
      {
        title: "美叶- 优质灵感辑录",
        desc: "美叶，为设计师，创意人提供有价值的设计参考。灵感采集，优质素材获取，时刻Follow最新流行设计趋势",
        logoUrl: "https://img1.imgtp.com/2022/08/01/NXeDEGQo.png",
        siteUrl: "https://www.meiye.art/",
      },
      {
        title: "站酷ZCOOL",
        desc: "站酷ZCOOL,中国设计师互动平台.深耕设计领域十五年,站酷聚集了1500万设计师、摄影师、插画师、艺术家、创意人,提供创意设计素材,正版商业高清图片,创意设计师群体中具有较高的影响力与号召力。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/oPt3cdfN.svg",
        siteUrl: "https://www.zcool.com.cn/",
      },
      {
        title: "花瓣网",
        desc: "花瓣网, 设计师寻找灵感的天堂！图片素材领导者，帮你采集、发现网络上你喜欢的事物。你可以用它收集灵感,保存有用的素材,计划旅行,晒晒自己想要的东西",
        logoUrl: "https://img1.imgtp.com/2022/08/01/zxaB9ukI.svg",
        siteUrl: "https://huaban.com/",
      },
    ],
  },
  {
    id: 8,
    label: "在线设计",
    order: 13,
    icon: "paint",
    children: [
      {
        title: "稿定设计",
        desc: "做图做视频在线设计神器",
        logoUrl: "https://st-gdx.dancf.com/assets/20190910-143541-210a.png",
        siteUrl: " https://www.gaoding.com/",
      },
      {
        title: "即时设计",
        desc: "即时设计是一款在线可协作的UI设计工具，是可协作的在线sketch、国内版figma，拥有海量的设计资源与素材，支持导入sketch格式的源文件。支持创建交互原型、获取设计标注、快速切图、团队协作等工作。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/VYavmEW6.svg",
        siteUrl: "https://js.design/",
      },
      {
        title: "Pixso",
        desc: "Pixso是一体化设计协作工具，助力产研设团队制作原型，UI/UX设计，视觉设计，低代码交付时获得更轻松流畅的工作体验，让团队协作更高效。支持Sketch，Figma格式。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/Uf2TD7rE.svg",
        siteUrl: "https://pixso.cn/",
      },
      {
        title: "figma",
        desc: "作为一个团队打造更好的产品。 使用 Figma 将设计、原型制作和收集反馈集中在一处。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/pC1inARh.svg",
        siteUrl: "https://www.figma.com/",
      },
      {
        title: "masterGo",
        desc: "MasterGo 是为团队协作而生的一站式在线产品设计工具，提供在线产品设计、原型图制作设计、网页开发设计、产品交互设计等功能，支持多人实时协作，可快速搭建设计系统。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/VHoRln7C.svg",
        siteUrl: "https://mastergo.com/",
      },
      {
        title: "墨刀",
        desc: "墨刀是产品设计一体化在线协同办公平台,集原型设计,线上版sketch设计师工具、流程图、思维导图为一体。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/mP5FRPGa.svg",
        siteUrl: "https://modao.cc/",
      },
    ],
  },
  {
    id: 9,
    label: "图标库",
    order: 8,
    icon: "smile",
    children: [
      {
        title: "iconfont",
        desc: "iconfont-国内功能很强大且图标内容很丰富的矢量图标库，提供矢量图标下载、在线存储、格式转换等功能。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/uS32Pn77.svg",
        siteUrl: "https://www.iconfont.cn/",
      },
      {
        title: "iconPark",
        desc: "IconPark, park your icon. Made by ByteDance",
        logoUrl: "https://img1.imgtp.com/2022/08/01/lmVQBz9D.svg",
        siteUrl: "https://iconpark.oceanengine.com/official",
      },
      {
        title: "Simple Icons",
        desc: "2316 Free SVG icons for popular brands",
        logoUrl: "https://img1.imgtp.com/2022/08/15/plCv7Eta.svg",
        siteUrl: "https://simpleicons.org/",
      },
      {
        title: "remixicon",
        desc: "Remix Icon 是一组为设计师和开发人员精心打造的开源中性风格系统符号。 所有图标均可免费用于个人和商业用途。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/zme4Qn1u.svg",
        siteUrl: "https://remixicon.com/",
      },
      {
        title: "fontawesome",
        desc: "世界上最受欢迎和最容易使用的图标集。 更多图标。 更多款式。 更多选择。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/0diR1NMz.svg",
        siteUrl: "https://fontawesome.com/",
      },
      {
        title: "bootstrap Icon",
        desc: "Bootstrap 官方开源 SVG 图标库",
        logoUrl: "https://img1.imgtp.com/2022/08/01/PtpT0XXB.svg",
        siteUrl: "https://icons.getbootstrap.com/",
      },
      {
        title: "material icons",
        desc: "Material Symbols 是我们最新的图标，将 2,500 多个字形整合到一个字体文件中，并具有多种设计变体。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/RX6sOmE6.svg",
        siteUrl: "https://fonts.google.com/icons",
      },
      {
        title: "xicons",
        desc: "icons合集",
        logoUrl: "https://img1.imgtp.com/2022/08/01/RR2ntqT3.png",
        siteUrl: "https://www.xicons.org/",
      },
    ],
  },
  {
    id: 10,
    label: "开发文档",
    order: 3,
    icon: "article",
    children: [
      {
        title: "es6入门教程",
        desc: "《ECMAScript 6 入门教程》是一本开源的 JavaScript 语言教程，全面介绍 ECMAScript 6 新引入的语法特性。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/Wqsx7eaq.png",
        siteUrl: "https://es6.ruanyifeng.com/",
      },
      {
        title: "现代 JavaScript 教程",
        desc: "以最新的 JavaScript 标准为基准。通过简单但足够详细的内容，为你讲解从基础到高阶的 JavaScript 相关知识。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/1eP9jbws.svg",
        siteUrl: "https://zh.javascript.info/",
      },
      {
        title: "MDN Web Docs",
        desc: "MDN Web Docs网站提供了有关开放式Web技术的信息，包括用于网站和渐进式Web应用程序的HTML、CSS和API。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/GuTvPEiV.svg",
        siteUrl: "https://developer.mozilla.org/zh-CN/",
      },
      {
        title: "菜鸟教程",
        desc: "菜鸟教程(www.runoob.com)提供了编程的基础技术教程, 介绍了HTML、CSS、Javascript、Python，Java，Ruby，C，PHP , MySQL等各种编程语言的基础知识。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/ew91WcyA.svg",
        siteUrl: "https://www.runoob.com/",
      },
      {
        title: "Typescript",
        desc: "TypeScript通过向语言中添加类型来扩展JavaScript，在运行代码之前捕捉错误并提供修复来加速开发体验。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/Zc4Tu6p1.svg",
        siteUrl: "https://www.typescriptlang.org/",
      },
      {
        title: "TypeScript 入门教程",
        desc: "从 JavaScript 程序员的角度总结思考，循序渐进的理解 TypeScript。",
        logoUrl: "https://img1.imgtp.com/2022/08/01/Zc4Tu6p1.svg",
        siteUrl: "https://ts.xcatliu.com/",
      },
      {
        title: "vuepress",
        desc: "Vue 驱动的静态网站生成器",
        logoUrl: "https://img1.imgtp.com/2022/07/14/aOJXDAoy.svg",
        siteUrl: "https://vuepress.vuejs.org/zh/",
      },
      {
        title: "vitpress",
        desc: "Vite & Vue powered static site generator.",
        logoUrl: "https://img1.imgtp.com/2022/07/14/aOJXDAoy.svg",
        siteUrl: "https://vitepress.vuejs.org/",
      },
    ],
  },
  {
    id: 11,
    label: "跨平台",
    order: 9,
    icon: "terminal",
    children: [
      {
        title: "electron",
        desc: "使用 JavaScript，HTML 和 CSS 构建跨平台的桌面应用程序。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/foCr0Ux6.svg",
        siteUrl: "https://www.electronjs.org/",
      },
      {
        title: "flutter",
        desc: "Flutter 官方文档中文版，包含 SDK 下载、最新特性介绍、代码示例、开发文档、中文社区等内容。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/r6eSSzhJ.svg",
        siteUrl: "https://flutter.cn/",
      },
      {
        title: "tauri",
        desc: "Tauri是一个框架，用于为所有主要桌面平台构建小巧、快速的二进制文件。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/jzfUL4sB.svg",
        siteUrl: "https://tauri.app/",
      },
    ],
  },
  {
    id: 12,
    label: "UI 组件库",
    order: 2,
    icon: "antd",
    children: [
      {
        title: "elemnt plus",
        desc: "a Vue 3 based component library for designers and developers",
        logoUrl: "https://img1.imgtp.com/2022/08/02/9mXFsLkU.svg",
        siteUrl: "https://element-plus.gitee.io/zh-CN/",
      },
      {
        title: "element",
        desc: "Element，一套为开发者、设计师和产品经理准备的基于 Vue 2.0 的桌面端组件库",
        logoUrl: "https://img1.imgtp.com/2022/08/02/9mXFsLkU.svg",
        siteUrl: "https://element.eleme.cn/#/zh-CN",
      },
      {
        title: "naive ui",
        desc: "Naive UI 是一个 Vue3 的组件库。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/8qC0npxI.svg",
        siteUrl: "https://www.naiveui.com/zh-CN/os-theme",
      },
      {
        title: "antd design  vue",
        desc: "基于Ant设计和Vue的企业级UI组件",
        logoUrl: "https://img1.imgtp.com/2022/07/20/h7f8CPif.svg",
        siteUrl: "https://www.antdv.com/docs/vue/introduce-cn",
      },
      {
        title: "antd design",
        desc: "antd 是基于 Ant Design 设计体系的 React UI 组件库，主要用于研发企业级中后台产品。",
        logoUrl: "https://img1.imgtp.com/2022/07/20/oiLDbwKz.svg",
        siteUrl: "https://ant.design/docs/react/introduce-cn",
      },
      {
        title: "TDesign",
        desc: "TDesign 是腾讯开源的企业级设计体系，提供了统一价值观，一致的设计语言和视觉风格，和开箱即用的 UI 组件库。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/dExogDF4.svg",
        siteUrl: "https://tdesign.tencent.com/",
      },
      {
        title: "arco design",
        desc: "Arco Design - 企业级产品的完整设计和开发解决方案",
        logoUrl: "https://img1.imgtp.com/2022/08/02/KAXw50Lz.svg",
        siteUrl: "https://arco.design/",
      },
      {
        title: "arco design mobile",
        desc: "让移动应用获得开箱即用的设计解决方案",
        logoUrl: "https://img1.imgtp.com/2022/08/02/KAXw50Lz.svg",
        siteUrl: "https://arco.design/mobile/react",
      },
      {
        title: "semi design",
        desc: "Create a consistent, good-looking, easy-to-use, and efficient user experience with a user-centric, content-first, and human-friendly design system",
        logoUrl: "https://img1.imgtp.com/2022/08/02/ZXHuJ4OO.svg",
        siteUrl: "https://semi.design/zh-CN/",
      },
      {
        title: "material-ui",
        desc: "React 组件用于更快速、更简便的 web 开发。你也可以建立你自己的设计系统，或者从 Material Design 开始。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/S1jSB1gh.svg",
        siteUrl: "https://v4.mui.com/zh/",
      },
      {
        title: "vuetify",
        desc: "Vuetify 是一个material风格的 Vue UI 库，包含手工制作的精美材料组件。不需要设计技能 - 创建令人惊叹的应用程序所需的一切都触手可及。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/6SR4ZcdA.svg",
        siteUrl: "https://vuetify.cn/zh-Hans/",
      },
    ],
  },
  {
    id: 13,
    label: "数据可视化",
    order: 10,
    icon: "bar-chart",
    children: [
      {
        title: "antv",
        desc: "AntV 是蚂蚁集团全新一代数据可视化解决方案，致力于提供一套简单方便、专业可靠、无限可能的数据可视化最佳实践。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/4cnGBdwF.svg",
        siteUrl: "https://antv.vision/zh",
      },
      {
        title: "Echarts",
        desc: "一个基于 JavaScript 的开源可视化图表库",
        logoUrl: "https://img1.imgtp.com/2022/08/02/7V0dtxyL.png",
        siteUrl: "https://echarts.apache.org/zh/index.html",
      },
      {
        title: "d3js",
        desc: "D3 is a JavaScript library for visualizing data with HTML, SVG, and CSS.",
        logoUrl: "https://img1.imgtp.com/2022/08/02/UW86e2eU.png",
        siteUrl: "https://d3js.org/",
      },
    ],
  },
  {
    id: 14,
    label: "打包构建",
    order: 11,
    icon: "webpack",
    children: [
      {
        title: "webpack",
        desc: "webpack主要目的是捆绑JavaScript文件以在浏览器中使用，但它也能够转换、捆绑或打包几乎任何资源或资产。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/R5mPhQzl.svg",
        siteUrl: "https://webpack.js.org/",
      },
      {
        title: "rollup",
        desc: "Rollup 是一个 JavaScript 模块打包器，可以将小块代码编译成大块复杂的代码，Rollup 对代码模块使用新的标准化格式，这些标准都包含在 JavaScript 的 ES6 版本中。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/8OQacDR9.png",
        siteUrl: "https://www.rollupjs.com/",
      },
      {
        title: "vite",
        desc: "下一代的前端工具链",
        logoUrl: "https://img1.imgtp.com/2022/08/02/HvVa18Bh.svg",
        siteUrl: "https://cn.vitejs.dev/",
      },
      {
        title: "esbuild",
        desc: "极速 JavaScript 打包器",
        logoUrl: "https://img1.imgtp.com/2022/08/02/xlLzGLvd.svg",
        siteUrl: "https://esbuild.docschina.org/",
      },
    ],
  },
  {
    id: 15,
    label: "Node 相关",
    order: 14,
    icon: "nodejs",
    children: [
      {
        title: "nodejs",
        desc: "Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine.",
        logoUrl: "https://img1.imgtp.com/2022/08/02/m1JW3UNh.svg",
        siteUrl: "https://nodejs.org/en/docs/",
      },
      {
        title: "express",
        desc: "高度包容、快速而极简的 Node.js Web 框架",
        logoUrl: "https://img1.imgtp.com/2022/08/02/zjcBTtLA.png",
        siteUrl: "https://expressjs.com/zh-cn/",
      },
      {
        title: "koa",
        desc: "基于 Node.js 平台的下一代 web 开发框架",
        logoUrl: "https://img1.imgtp.com/2022/08/02/yyufazQi.svg",
        siteUrl: "https://www.koajs.com.cn/",
      },
      {
        title: "eggjs",
        desc: "企业级node框架",
        logoUrl: "https://img1.imgtp.com/2022/08/02/YWpoPkid.svg",
        siteUrl: "https://www.eggjs.org/zh-CN",
      },
      {
        title: "nestjs",
        desc: "NestJS是一个用于构建高效、可扩展节点的框架。js web应用程序。它使用现代JavaScript，使用TypeScript构建，并结合了OOP（面向对象编程）、FP（函数式编程）和FRP（函数式反应式编程）的元素。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/hmS5JokV.svg",
        siteUrl: "https://nestjs.com/",
      },
      {
        title: "typeorm",
        desc: "TypeORM is an ORM that can run in NodeJS, Browser, Cordova, PhoneGap, Ionic, React Native, NativeScript, Expo, and Electron platforms and can be used with TypeScript and JavaScript ",
        logoUrl: "https://img1.imgtp.com/2022/08/02/3XEYhRns.png",
        siteUrl: "https://typeorm.io/",
      },
      {
        title: "Sequelize",
        desc: "Sequelize是一种现代类型脚本和节点。用于Postgres、MySQL、MariaDB、SQLite和SQL Server等的js ORM。具有可靠的事务支持、关系、即时和延迟加载、读取复制等功能。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/QrG5TKDK.svg",
        siteUrl: "https://sequelize.org/",
      },
      {
        title: "prisma",
        desc: "Next-generation Node.js and TypeScript ORM",
        logoUrl: "https://img1.imgtp.com/2022/08/02/OMcSQXeM.svg",
        siteUrl: "https://www.prisma.io/",
      },
    ],
  },
  {
    id: 16,
    label: "小程序相关",
    order: 15,
    icon: "wechat",
    children: [
      {
        title: "微信小程开发文档",
        desc: "微信开发者平台文档",
        logoUrl: "https://img1.imgtp.com/2022/08/02/aCDXALR8.svg",
        siteUrl: "https://developers.weixin.qq.com/miniprogram/dev/framework/",
      },
      {
        title: "支付宝小程序",
        desc: "支付宝小程序官网",
        logoUrl: "https://img1.imgtp.com/2022/08/02/npF0F65s.svg",
        siteUrl: "https://mini.open.alipay.com/channel/miniIndex.htm",
      },
      {
        title: "QQ小程序",
        desc: "QQ小程序是连接年轻用户的新方式，覆盖8亿新生代活跃网民。轻便快捷的开发模式，将能在QQ内被轻松获取和传播",
        logoUrl: "https://img1.imgtp.com/2022/08/02/N5zccWs8.svg",
        siteUrl: "https://q.qq.com/miniapp",
      },
      {
        title: "uni-app",
        desc: "uni-app多端开发,开发一次同时生成App、小程序、H5",
        logoUrl: "https://img1.imgtp.com/2022/08/02/zaPkreMS.svg",
        siteUrl: "https://uniapp.dcloud.net.cn/",
      },
      {
        title: "taro",
        desc: "Taro 是一个开放式跨端跨框架解决方案，支持使用 React/Vue/Nerv 等框架来开发 微信 / 京东 / 百度 / 支付宝 / 字节跳动 / QQ / 飞书 小程序 / H5 / RN 等应用。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/vLIb0Etb.svg",
        siteUrl: "https://taro-docs.jd.com/taro/docs/",
      },
      {
        title: "kbone",
        desc: "kbone 是一个致力于微信小程序和 Web 端同构的解决方案。",
        logoUrl: "https://img1.imgtp.com/2022/07/29/2VLOweww.svg",
        siteUrl: "https://github.com/Tencent/kbone",
      },
    ],
  },
  {
    id: 17,
    label: "办公协作",
    order: 17,
    icon: "document",
    children: [
      {
        title: "语雀",
        desc: "十万阿里人都在用的笔记与文档知识库",
        logoUrl:
          "https://gw.alipayobjects.com/zos/rmsportal/UTjFYEzMSYVwzxIGVhMu.png",
        siteUrl: "https://www.yuque.com/dashboard",
      },
      {
        title: "腾讯文档",
        desc: "腾讯文档是一款可多人协作的在线文档，可同时编辑Word、Excel和PPT文档，云端实时保存。可针对QQ、微信好友设置文档访问、编辑权限，支持多种版本Word、Excel和PPT文档模板。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/QI9mKHQI.svg",
        siteUrl: "https://docs.qq.com/",
      },
      {
        title: "飞书",
        desc: "飞书——先进企业协作与管理平台。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/ETFn1LR5.svg",
        siteUrl: "https://www.feishu.cn/",
      },
      {
        title: "腾讯会议",
        desc: "基于腾讯20多年音视频通讯经验，腾讯会议提供一站式音视频会议解决方案，让您能随时随地体验高清流畅的会议以及会议协作。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/ZNlcpdq3.svg",
        siteUrl: "https://meeting.tencent.com/",
      },
      {
        title: "google文档",
        desc: "使用 Google 文档创建和协作处理在线文档。在任意设备上安全地实时共享内容，与他人一起编辑文档。",
        logoUrl: "https://img1.imgtp.com/2022/08/02/IS9xjnYg.svg",
        siteUrl: "https://www.google.com/intl/zh-CN/docs/about/",
      },
      {
        title: "石墨文档",
        desc: "全新一代云端 Office，面向未来的办公软件",
        logoUrl: "https://img1.imgtp.com/2022/08/02/nCgMfXfr.svg",
        siteUrl: "https://shimo.im/",
      },
      {
        title: "博思白板",
        desc: "BoardMix在线协作白板，集思维导图，流程图、多维表格，笔记文档多种创意表达能力于一体，激发团队创造力无限延伸，免费在线使用。",
        logoUrl: "https://img1.imgtp.com/2022/08/03/6OEKSFqN.svg",
        siteUrl: "https://boardmix.cn/",
      },
    ],
  },
  {
    id: 18,
    label: "Node 包管理",
    order: 16,
    icon: "npm",
    children: [
      {
        title: "npm",
        desc: "node包管理器",
        logoUrl: "https://img1.imgtp.com/2022/08/11/5ydMpWld.svg",
        siteUrl: "https://www.npmjs.com/",
      },
      {
        title: "yarn",
        desc: "Fast, reliable, and secure dependency management.",
        logoUrl: "https://img1.imgtp.com/2022/08/11/YhH2xLpP.svg",
        siteUrl: "https://yarnpkg.com/",
      },
      {
        title: "pnpm",
        desc: "pnpm - 速度快、节省磁盘空间的软件包管理器",
        logoUrl: "https://img1.imgtp.com/2022/08/11/oxgyZT14.svg",
        siteUrl: "https://www.pnpm.cn/",
      },
    ],
  },
  {
    id: 19,
    label: "视频学习",
    order: 18,
    icon: "bilibili",
    children: [
      {
        title: "慕课网",
        desc: "慕课网（IMOOC）是IT技能学习平台。慕课网(IMOOC)课程涉及JAVA、前端、Python、大数据等60类主流技术语言，覆盖了面试就业、职业成长、自我提升等需求场景，帮助用户实现从技能提升到岗位提升的能力闭环。",
        logoUrl: "https://img1.imgtp.com/2022/08/13/EpLWjvFh.svg",
        siteUrl: "https://www.imooc.co/",
      },
      {
        title: "极客学院",
        desc: "极客学院作为专业IT职业在线教育平台,拥有海量高清IT职业课程,涵盖30+个技术领域。",
        logoUrl: "https://img1.imgtp.com/2022/08/13/LWUo5A0k.png",
        siteUrl: "https://www.jikexueyuan.com/",
      },
      {
        title: "哔哩哔哩",
        desc: "bilibili是国内知名的视频弹幕网站，这里有及时的动漫新番，活跃的ACG氛围，有创意的Up主。大家可以在这里找到许多欢乐。",
        logoUrl: "https://img1.imgtp.com/2022/08/13/RpMI0CQf.svg",
        siteUrl: "https://www.bilibili.com/",
      },
    ],
  },
  {
    id: 20,
    label: "面试刷题",
    order: 18,
    icon: "leetCode",
    children: [
      {
        title: "大厂面试题每日一题",
        desc: "山月的全栈进阶之路",
        logoUrl: "https://q.shanyue.tech/assets/img/logo.b8798990.png",
        siteUrl: "https://q.shanyue.tech/",
      },
      {
        title: "力扣（LeetCode）",
        desc: "备战技术面试？力扣提供海量技术面试资源，帮助你高效提升编程技能，轻松拿下世界 IT 名企 Dream Offer。",
        logoUrl: "https://img1.imgtp.com/2022/08/16/wy1wz8Fs.svg",
        siteUrl: "https://leetcode.cn/",
      },
      {
        title: "面试鸭",
        desc: "专业面试刷题网站，助你成为面试达人！支持自由组卷、在线刷题、校招社招斩获大厂offer，求职必备！",
        logoUrl: "https://img1.imgtp.com/2022/08/13/vARJ3HQW.png",
        siteUrl: "https://www.mianshiya.com/",
      },
    ],
  },
];
